name: Deploy Streamlit Docker App to EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" | base64 -d > key.pem
        chmod 400 key.pem

    - name: Deploy to EC2 and restart Docker in screen
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Clone if not present
          if [ ! -d "chatbot1" ]; then
            git clone https://github.com/sudharshandollu/chatbot1.git
          fi
          cd chatbot1
          git pull origin master

          # Kill old Docker container and screen
          docker stop chatbot || true
          docker rm chatbot || true
          screen -S chatbot -X quit || true

          # Rebuild image
          docker build -t streamlit-chatbot .

          # Start in screen
          screen -dmS chatbot bash -c '
            docker run --env-file ~/chatbot1/.env --name chatbot -p 8501:8501 streamlit-chatbot
          '
        EOF
